import { ContextProvider } from "./context/ContextAPI";
import {  Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins(
  { 
    subsets: ["latin"],
    variable: "--font-poppins", 
    weight: ["200", "300", "400", "500", "600", "700"]
  }
);



export const metadata = {
  title: "HAPPY - SHOPPING",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}`} >
      <body>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
